application: eng-cache-700
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on
- appstats: on

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest